name: build
on: [push, pull_request]
jobs:
  main:
    runs-on: macos-latest
    env:
      THEOS: /opt/theos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: brew install ldid make xz git
      - name: Setup Theos
        run: |
          sudo mkdir -p $THEOS
          sudo chown $(whoami) $THEOS
          git clone --recursive https://github.com/theos/theos.git $THEOS
      - name: Download SDKs (only iPhoneOS)
        run: |
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mkdir -p $THEOS/sdks
          cp -r sdks-master/iPhoneOS*.sdk $THEOS/sdks/ || true  # Chỉ copy iPhoneOS để tránh lỗi TVOS
          rm -rf master.zip sdks-master
      - name: Link System SDK (fallback)
        run: |
          ln -s /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk $THEOS/sdks/iPhoneOS.sdk || true
      - name: Debug - List Files & SDKs
        run: |
          ls -la
          ls -la $THEOS/sdks || true
          cat Makefile || true
          cat control || true
      - name: Build package
        run: THEOS=$THEOS make package FINALPACKAGE=1
      - uses: actions/upload-artifact@v4
        with:
          name: dylib
          path: packages/*.deb
