name: build
on: [push, pull_request]
jobs:
  main:
    runs-on: macos-latest
    env:
      THEOS: theos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Thêm lại step này để pull code repo
      - name: Install Dependencies
        run: brew install ldid make xz
      - name: Setup Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          path: theos
          submodules: recursive
      - name: Link System SDK
        run: |
          mkdir -p $THEOS/sdks
          ln -s /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk $THEOS/sdks/iPhoneOS.sdk || true
      - name: Debug - List Files & SDKs
        run: |
          ls -la
          ls -la $THEOS/sdks || true
          cat Makefile || true
          cat control || true
      - name: Build package
        run: make package FINALPACKAGE=1
      - uses: actions/upload-artifact@v4
        with:
          name: dylib
          path: packages/*.deb